In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("spam_ham_dataset.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'spam_ham_dataset.csv'

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving spam_ham_dataset.csv to spam_ham_dataset.csv

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("spam_ham_dataset.csv")

In [ ]:
df

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0
...,...,...,...,...
5166,1518,ham,Subject: put the 10 on the ft\r\nthe transport...,0
5167,404,ham,Subject: 3 / 4 / 2000 and following noms\r\nhp...,0
5168,2933,ham,Subject: calpine daily gas nomination\r\n>\r\n...,0
5169,1409,ham,Subject: industrial worksheets for august 2000...,0
5170,4807,spam,Subject: important online banking alert\r\ndea...,1

In [ ]:
df.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [ ]:
import sklearn as sk

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
x=df["text"]

In [ ]:
y=df["label"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

4722    Subject: \r\nthe permanent fix to penis growth...
208     Subject: payment confirmation p 9990835\r\n- -...
4472    Subject: dec 00\r\ndaren - i need to get with ...
1109    Subject: 2 nd rev mar . 2000 josey ranch nom\r...
440     Subject: energy operations , gas operations - ...
                              ...
1796    Subject: hpl nom for dec . 16 - 18 , 2000\r\np...
4297    Subject: formation of enron management committ...
3307    Subject: schedule\r\nhere is our schedule . i ...
1098    Subject: hpl noms . for jan . 19 , 2001\r\n( s...
2114    Subject: this week ' s woodworking tip . . . f...
Name: text, Length: 4136, dtype: object

In [ ]:
x_test

2286    Subject: tenaska iv 4 / 01\r\nwe need to chang...
780     Subject: but it ' s not interesting\r\nwed , 0...
4221    Subject: not as rough list\r\ni spoke to sabra...
295     Subject: soul mate\r\none of your buddies hook...
905     Subject: 29 th changes\r\n- - - - - - - - - - ...
                              ...
3724    Subject: urgent assistance\r\ndear friend ,\r\...
453     Subject: dave n out of pocket next week , beyo...
1760    Subject: dave n out until july 5 th\r\ni will ...
4242    Subject: as hard as you can and she still want...
4148    Subject: hpl nom for december 12 , 2000\r\n( s...
Name: text, Length: 1035, dtype: object

In [ ]:
y_train

4722    spam
208     spam
4472     ham
1109     ham
440      ham
        ...
1796     ham
4297     ham
3307     ham
1098     ham
2114     ham
Name: label, Length: 4136, dtype: object

In [ ]:
y_test

2286     ham
780     spam
4221     ham
295     spam
905      ham
        ...
3724    spam
453      ham
1760     ham
4242    spam
4148     ham
Name: label, Length: 1035, dtype: object

In [ ]:
vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=50000,
    ngram_range=(1,2)
)

x_train_vec = vectorizer.fit_transform(x_train)
x_test_vec = vectorizer.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression()

In [ ]:
model

LogisticRegression()

In [ ]:
model.fit(x_train_vec,y_train)

LogisticRegression()

In [ ]:
y_pred=model.predict(x_test_vec)

In [ ]:
y_pred

array(['ham', 'spam', 'ham', ..., 'ham', 'spam', 'ham'], dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

In [ ]:
accuracy

0.9893719806763285

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
recall = recall_score(y_test, y_pred,pos_label='spam')

In [ ]:
recall

0.9766666666666667

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
precision = precision_score(y_test, y_pred,pos_label='spam')

In [ ]:
precision

0.9865319865319865